### ISSUE TITLE
inflow condition

### ISSUE THREAD

**Issue by migueldvb** [piernik-dev/piernik#123]
I am running a binary system setup in 3D cartesian coordinates. I would like to enforce a wind outflow at some radial distance from the origin with the initial wind density and speed. Is there any problem setup that has a similar inflow requirement or where should it be defined?

**Comment by gawrysz** [comment]
If you want to impose boundary conditions inside computational domain, you may use `problem_customize_solution` hook. You can add any routine that will be called right after sweeps and modify the fluid data directly according to your geometrical criteria. Such approach was already done in problems `wt4` and `streaming_global`.

**Comment by migueldvb** [comment]
Thank you. I will use this method.
