### ISSUE TITLE
initial velocity

### ISSUE THREAD

**Issue by migueldvb** [piernik-dev/piernik#128]
I have tested a simple setup with a radial wind outflow in cartesian coordinates and found an strange problem with an initial velocity in the `y` component. This velocity appears even when the all the `fl%imx` and `fl%imy` are defined as zero. I have also tried removing gravity and coriolis modules in the problem files below. I wonder if you have found this issue before

https://github.com/migueldvb/piernik/blob/wind/problems/wind/initproblem.F90
https://github.com/migueldvb/piernik/blob/wind/problems/wind/piernik.def

**Comment by migueldvb** [comment]
This is an example of the initial conditions of the velocity_y component in a problem with zero initial velocity in `initproblem.F90`. The plots show the velocity arrows in the x-z and y-z planes.

![wind_tst_0000_slice_z_velocity_y](https://cloud.githubusercontent.com/assets/678759/6712527/7124c98e-cd63-11e4-8032-632795d0a840.png)

![wind_tst_0000_slice_x_velocity_y](https://cloud.githubusercontent.com/assets/678759/6712917/9befba0a-cd65-11e4-8921-4fa4b169344a.png)


This test is available in https://github.com/migueldvb/piernik/releases/tag/v0.1

**Comment by Xarthisius** [comment]
You're using isothermal gas (`#define ISO` in `piernik.def`) and yet you assign some values to *u* using *fl%ien*, which is in this case -1. This happily overwrites some random portion of memory giving you that magic velocity field. Comment out lines 129 and 130 in `init_problem.F90` and you'll get what you want :-)

```
>>> import yt
>>> ds = yt.load("wind_tst_0010.h5")
>>> dd = ds.all_data()
>>> dd["velocity_magnitude"].max()
0.0 cm/s
```

I'd recommend using `./setup --debug` while developing new problem. This would be immediately caught by compiler during runtime.

**Comment by migueldvb** [comment]
Thank you for noticing the problem. I did not realize that ien has a constant value. It is very useful to enable  the debug flags with that option.
