### ISSUE TITLE
Use values from FLUID_IONIZED namelist in initproblem.F90

### ISSUE THREAD

**Issue by migueldvb** [piernik-dev/piernik#130]
I wonder if it is possible to get values from the namelists of parameters that are defined in problem.par into initproblem.F90 using the same method as for PROBLEM_CONTROL or there is some reason why this should not be done.  I would like to read the cs_iso parameter from FLUID_IONIZED instea of using the get_cs function because there is no magnetic pressure in the problem and this value will be always the same.

**Comment by gawrysz** [comment]
You can read same namelists multiple times if you really need to. The 'alien' namelists should be read without calling all those fancy routines to avoid putting the read values to the log multiple times.

I think that in your case  `flind` from `fluidindex` will give you the value you need as `flind%ion%cs`.

**Comment by migueldvb** [comment]
Thank you very much. That is what I needed. I had missed the `set_fluid_index` routine that sets the elements of the fluid component.
