### ISSUE TITLE
outflow boundary conditions

### ISSUE THREAD

**Issue by migueldvb** [piernik-dev/piernik#136]
I have tried to use 'out' and 'diode' boundary conditions in a wind accretion simulation and noticed that a narrow stripe appears at the left x boundary that has higher density and is introduced probably by the boundary. The imposed outflow is spherically symmetric with respect to the origin and the overdense region builds up slowly perhaps because the flow is roughly parallel to the boundary. 

![chcyg_lowres_tst_0009_slice_z_density](https://cloud.githubusercontent.com/assets/678759/6834250/277416f4-d309-11e4-9717-d244825a4988.png)

**Comment by gawrysz** [comment]
With such high symmetry you can try reflecting boundary on xl.

**Comment by migueldvb** [comment]
Thank you. Reflecting boundary works well.
