### ISSUE TITLE
coordinates corresponding to state vector u

### ISSUE THREAD

**Issue by migueldvb** [piernik-dev/piernik#137]
I have tried some experiments to solve the problem with the non-inertial forces. I think that the problem is in the coordinates used for the centrifugal forces. The conserved fluid quantities for each sweep
are given in the RTVD module by:

`transpose(cg%get_sweep(cdim,i1,i2))`

How can I get the x and y coordinates for this vector of conserved variables to be used in the expression?

`+2.0 * omega * u(:, iarr_all_my)/u(:, iarr_all_dn) + omega**2 * cg%x`

**Comment by Xarthisius** [comment]
I don't understand the question... `cg%x` and `cg%y` **are** the *x* and *y* coordinates for `u`. Your expression looks valid

**Comment by migueldvb** [comment]
Thanks, then the problem may be somewhere else.

**Comment by Xarthisius** [comment]
Could you write down formulas that you want to implement using latex notation?
Right now you have:

 * ` 2 \Omega v_y + \Omega^2 * x` in *x* direction
 * `-2 \Omega v_y + \Omega^2 * y` in *y* direction

Is the latter correct? Shouldn't it be `-2 \Omega v_x` ?

**Comment by migueldvb** [comment]
Yes, the formulas for the acceleration are:

```
 acc_x = 2 * \Omega * v_y + \Omega^2 * x
 acc_y =  -2 * \Omega * v_x + \Omega^2 * y
```
I think this will be the same that we have in `non_inertial.F90`. The velocity is calculated by the momentum density divided by the mass density in the x and y directions. 

```
      do ifl = 1, flind%fluids
         select case (sweep)
            case (xdim)
               rotacc(:, ifl) = +2.0 * omega * u(:, iarr_all_my(ifl))/u(:, iarr_all_dn(ifl)) + omega**2 * cg%x
            case (ydim)
               rotacc(:, ifl) = -2.0 * omega * u(:, iarr_all_mx(ifl))/u(:, iarr_all_dn(ifl)) + omega**2 * cg%y
             case default
               rotacc(:, ifl) = 0.0
         end select
      enddo
```

**Comment by Xarthisius** [comment]
Trick is that `iarr_all_m{x..z}` change their meaning inside `relaxing_tvd` as we're swapping indices, since we're using one dimensional solver in dimensionally split algorithm. For `sweep == ydim` `u(:, iarr_all_mx)/u(:, iarr_all_dn)` is actually velocity in *y* direction.

**Comment by migueldvb** [comment]
Ah, thanks for noticing that. Then for the y sweep the y component of the velocity  will be u(:, iarr_all_my)/u(:, iarr_all_dn)
```
rotacc(:, ifl) = -2.0 * omega * u(:, iarr_all_my(ifl))/u(:, iarr_all_dn(ifl)) + omega**2 * cg%y
```

I think this needs to be corrected also in the coriolis module.

**Comment by Xarthisius** [comment]
Nope, for sweep *y*, y-component of velocity is `u(:, iarr_all_mx) / u(:, iarr_all_dn)`, but you want to have x-component which is `u(:, iarr_all_my)/u(:, iarr_all_dn)`

**Comment by migueldvb** [comment]
Sorry, that is what I meant. I have added this change and the latex equations to the PR for the non-inertial forces module.
