### ISSUE TITLE
-fstack-arrays / -fno-stack-arrays

### ISSUE THREAD

**Issue by gawrysz** [piernik-dev/piernik#207]
Recently I've changed the default to `-fno-stack-arrays` (equivalent of Intel's `-fheap-arrays`) because it is safer. 

- Enabling arrays placed on stack gives better performance (I've seen ~20% improvement in 3D, a bit less in X-Z 2D). This is because we can avoid indirect calls to `malloc()` and `free()` millions of times for local and for temporary arrays. The problem is that sometimes is is used for huge arrays as well, which leads to non-obvious segfaults. Typically Linux machines offer 8192 kB of stack by default (which usually can be increased because the hard limit is "unlimited"). This is just few kB short when your 2D domain is 1024×1024 or 3D domain is 96×96×96. There are a number of workarounds for this, each has its own limitations:
    - Call `ulimit -s unlimited` before running Piernik if the system permits.
    - Use more processes, so no single scalar array can reach 8 MB storage (means less than about 1M cells in local domain, including boundary cells).
    - Set `AMR_bsize` to force grid decomposition to blocks smaller than 1M cells in `MPI_BLOCKS` namelist in the `problem.par` (requires domain size to be divisible by `AMR_bsize`).
    - Implement additional block splitting in [decomposition.F90](https://github.com/piernik-dev/piernik/blob/master/src/grid/decomposition.F90) in a way that does not require any divisibility. This is hard to be done reliably and automatically as the stack limit seems to be obtainable by an ugly `call system("ulimit -s > _some_file_")` (or `call execute_command_line(...)`) and then interpreting that `_some_file_` or by wrapping piernik in some script to provide an estimate when to split local domains and to how many pieces.
- Restoring the default behavior (local and temporary arrays land on the heap) is safe because it removes possibility of getting segfault due to too big local domain but results in some performance penalty. Most of the extra CPU load currently comes from few files that operate on 1D vectors:
    - [rtvd.F90](https://github.com/piernik-dev/piernik/blob/master/src/scheme/rtvd_split/rtvd.F90#L306) allocates a lot of local arrays.
    - [flux routines](https://github.com/piernik-dev/piernik/blob/master/src/fluids/neutral/initneutral.F90#L227) (ionized and dust too) do a lot of temporary array creation.

    There is little, if any, influence on multigrid solver. I bet that this also won't be an issue for any unsplit MHD solver that we might want to implement in the future.

IMO the best solution would be to find a way to rewrite these routines to avoid these calls to `malloc()` *and* maintain performance close to `-fstack-arrays`. In case of `rtvd` perhaps reusing arrays would be sufficient (even for non-squared domains it is called few hundred times with one length before it changes to another length). It is less clear to me how to rewrite flux routines. Everything I quickly tried as yet (explicit loop, `forall` construct) resulted in further performance degradation. Manual optimization for SIMD-friendly code will likely result in human-unfriendly code.

**Comment by gawrysz** [comment]
Work in progress: https://github.com/gawrysz/piernik/tree/no-stack-arrays

**Comment by gawrysz** [comment]
Use of '-fno-stack-arrays' is suggested as a default, safe setting. See comments and graphs in #208.

**Comment by Artoria2e5** [comment]
> This is hard to be done reliably and automatically as the stack limit seems to be obtainable by an ugly `call system("ulimit -s > _some_file_")` (or `call execute_command_line(...)`) and then interpreting that `_some_file_`

Sorry for replying to this so late (I was mindlessly looking for how people are using this flag), but FWIW the limit comes from POSIX `getrlimit()`. The relevant section of `bash`'s implementation of `ulimit -r` is https://github.com/bminor/bash/blob/f3a35a2d601a55f337f8ca02a541f8c033682247/builtins/ulimit.def#L627-L648.

**Comment by gawrysz** [comment]
Thank you for your feedback! It was good point to check whether current version of Piernik behaves in similar way as the old one :)

Our priority is to provide safe defaults that do not fail in a non-obvious way. Experienced user can create his/her own compiler settings with `-fstack-arrays` for extra performance gain at his/her own risk.

The code compiled with `-fstack-arrays` works correctly for most reasonable configurations but inexperienced users may easily run into the problematic sets of parameters like AMR block size greater than 64<sup>3</sup> or big uniform domain decomposed into too small number of processes.
